"""create books table

Revision ID: 5b35dd9fedc4
Revises: 4b93eb525fc4
Create Date: 2026-01-22 17:38:39.118365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b35dd9fedc4'
down_revision: Union[str, Sequence[str], None] = '4b93eb525fc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('resume', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'resume')
    # ### end Alembic commands ###
